services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=restaurant'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'